### ISSUE TITLE
'dict' object has no attribute 'has_key' error

### ISSUE THREAD

**Issue by hamza-tm** [wouterboomsma/eigency#1]
Hi, I attempted a `pip install eigency` (v0.61) on python 3.5.1 and received the following error in `eigency/setup.py", line 44`
```
        if dist.command_obj.has_key('install'):
    AttributeError: 'dict' object has no attribute 'has_key'
```

Apparently `dict.has_key` was removed in python 3.x (one would use `in` instead).

Is this intentional? Is python 3 supported?

Thanks,
Hamza

**Comment by wouterboomsma** [comment]
Hi Hamza

No, this is not intentional. I haven't tested it on Python3, so there are
probably a few minor errors
like this that need to be fixed. As far as I can see, there are not really
any substantial things in
the eigency library itself that are incompatible with python3 (it's mostly
numpy stuff). If you feel
up to it, it would be great if you could that it works with Python3 - and I
certainly welcome any
pull requests with the necessary changes.

Cheers,
Wouter

**Comment by hamza-tm** [comment]
Sure! I'll have a look

**Comment by hamza-tm** [comment]
PR here: https://github.com/wouterboomsma/eigency/pull/2

**Comment by wouterboomsma** [comment]
PR merged. Thanks.
