### ISSUE TITLE
Bugs with creating an Eigen Array in a pyx file and returning it with ndarray function

### ISSUE THREAD

**Issue by trago** [wouterboomsma/eigency#6]
Hello, before start I would like to give thanks for the work you have done. I think there are some bugs.

I have this example:
```
Eigen::ArrayXXd create_mat()
{
  Eigen::ArrayXXd sigms(3, 3);

  for(int n = 0; n<sigms.cols(); n++)
    for (int m = 0; m < sigms.rows(); m++)
      sigms(m, n) = 1.0;

  return sigms;
}
```

And have two versions of correspongind cython wrapping as in a file called kernel.pyx:

### Version 1
```
def create_mat1():
    cdef ArrayXXd sigms = create_mat()
    return ndarray(sigms)
```
### Version 2
```
def create_mat1():
    return ndarray(create_mat())
```

In my python code a have the following:
```
import kernel

m1 = kernel.create_mat1()
m2 = kernel.create_mat2()

print(m1)
print(m2)
```

The output is the following:

```
[[  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
```

It is clear that there is something wrong. Both functions should give the same result.

**Comment by wouterboomsma** [comment]
Hi,
Thanks.
Actually, this is expected behaviour - although I'll be the first to admit that it is not very obvious. The problem with the first case is that you end up referring to memory that belonged to a temporary. This occurs in the special case of non-reference return values, and there is a section in the documentation where I've attempted to explain it - but perhaps not sufficiently clearly. The short story is that you should use `ndarray_copy()` rather than `ndarray()` when returning values (non-references) from a C++ function. This will ensure that a copy is made of the underlying data. The second case works because eigency is able to automatically detect that you are referring to a temporary (an r-value reference), and automatically makes a copy in this case.

### The long story
The `ndarray` function is defined like this:
```c++
template <typename Derived>
inline PyArrayObject *ndarray(Eigen::PlainObjectBase<Derived> &m) {
```
This means that it cannot differentiate between a c++ function returning a reference and a function returning a value, because they will both match this function definition. If the code is compiled with a c++11 compliant compiler, another definition is made available:
```c++
template <typename Derived>
inline PyArrayObject *ndarray(Eigen::PlainObjectBase<Derived> &&m) {
```
which will detect the case from your version2 example, and automatically make a copy. One could argue that making a copy should be the default (so that errors like your's don't occur), but that would mean that there are cases where you get a copy when you expected a view). As a guiding principle in Eigency, we reuse memory whenever possible, which is why it works like it does. However, you can always override these defaults by calling `ndarray_view` or `ndarray_copy` explicitly.

**Comment by trago** [comment]
Hi, thank you very much for your answer, it makes sense.

I really like this project since makes the code more clean.

Thanks again
